---
- name: Download Minikube binary
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Cleanup previous state
  shell: |
    minikube delete --all --purge
    rm -rf /root/.kube /root/.minikube
  ignore_errors: yes
  become: yes
  environment:
    HOME: /root

- name: Start Minikube (Driver NONE)
  shell: |
    minikube start \
      --driver=none \
      --force \
      --container-runtime=docker \
      --extra-config=kubeadm.ignore-preflight-errors=NumCPU \
      --listen-address=0.0.0.0
  become: yes
  environment:
    HOME: /root

- name: Fix permissions for kube config
  file:
    path: /root/.kube
    owner: root
    group: root
    recurse: yes
  become: yes

- name: Wait for nodes to be ready
  command: kubectl wait --for=condition=Ready nodes --all --timeout=120s
  become: yes
  environment:
    HOME: /root

- name: Enable Addons (Ingress & Dashboard)
  shell: minikube addons enable {{ item }}
  loop:
    - ingress
    - dashboard
  become: yes
  environment:
    HOME: /root

- name: Wait for Dashboard to be created
  shell: kubectl get service kubernetes-dashboard -n kubernetes-dashboard
  register: dash_check
  until: dash_check.rc == 0
  retries: 12
  delay: 10
  become: yes
  environment:
    HOME: /root


- name: Start Kubernetes API Proxy
  shell: |
    nohup kubectl proxy --address='0.0.0.0' --accept-hosts='.*' --port=8001 --disable-filter=true > /tmp/kubectl-proxy.log 2>&1 &
  become: yes
  async: 60
  poll: 0
  ignore_errors: yes
  environment:
    HOME: /root
- name: Get external IP of the VM
  shell: curl -s https://ifconfig.me
  register: external_ip
  changed_when: false

- name: Show Minikube Dashboard URL
  debug:
    msg:
      - "Minikube is READY"
      - "1. Open this URL in browser: http://{{ external_ip.stdout }}:8001/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/"
      - "2. If you see 404, wait 30 seconds and refresh (pods are starting)."

