---
- name: Download Minikube binary
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Cleanup previous Minikube state
  command: minikube delete
  ignore_errors: yes
  become: yes
  environment:
    HOME: /root

- name: Start Minikube (with NONE driver)
  shell: |
    minikube start \
      --driver=none \
      --force
  become: yes
  environment:
    HOME: /root

- name: Wait for Minikube to be ready
  command: kubectl wait --for=condition=Ready nodes --all --timeout=120s
  become: yes
  environment:
    HOME: /root

- name: Enable Minikube addons
  shell: minikube addons enable ingress
  become: yes
  environment:
    HOME: /root

- name: Start kubectl proxy (background)
  shell: |
    nohup kubectl proxy \
      --address='0.0.0.0' \
      --port=8001 \
      --accept-hosts='^.*$' \
      --disable-filter=true \
      > /var/log/kubectl-proxy.log 2>&1 &
  become: yes
  environment:
    HOME: /root
