---
# 1. Очищення конфліктних репозиторіїв
- name: Remove all conflicting repository files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/sources.list.d/docker.list
    - /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
    - /etc/apt/sources.list.d/kubernetes.list

# 2. Встановлення системних залежностей
- name: Update apt and install core dependencies
  apt:
    name:
      - curl
      - wget
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - software-properties-common
      - conntrack
      - socat
      - iproute2
    state: present
    update_cache: yes
    force_apt_get: yes

# 3. Встановлення crictl
- name: Download and install crictl
  shell: |
    VERSION="v1.30.0"
    curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${VERSION}/crictl-${VERSION}-linux-amd64.tar.gz" --output crictl.tar.gz
    tar zxvf crictl.tar.gz -C /usr/local/bin
    rm -f crictl.tar.gz
  args:
    creates: /usr/local/bin/crictl

# 4. Встановлення cri-dockerd (Міст між Docker та Kubernetes)
- name: Install cri-dockerd
  shell: |
    VERSION="0.3.15"
    curl -L "https://github.com/Mirantis/cri-dockerd/releases/download/v${VERSION}/cri-dockerd-${VERSION}.amd64.tgz" --output cri-dockerd.tgz
    tar zxvf cri-dockerd.tgz
    install -o root -g root -m 0755 cri-dockerd/cri-dockerd /usr/local/bin/cri-dockerd
    
    # Налаштування systemd сервісів
    wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service
    wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket
    mv cri-docker.service cri-docker.socket /etc/systemd/system/
    sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service
    
    systemctl daemon-reload
    systemctl enable --now cri-docker.socket
    systemctl enable --now cri-docker.service
    rm -rf cri-dockerd.tgz cri-dockerd
  args:
    creates: /usr/local/bin/cri-dockerd

# 5. Встановлення CNI plugins (Мережа для Pods)
- name: Install CNI plugins
  shell: |
    mkdir -p /opt/cni/bin
    CNI_VERSION="v1.4.0"
    curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-linux-amd64-${CNI_VERSION}.tgz" --output cni-plugins.tgz
    tar -C /opt/cni/bin -xzf cni-plugins.tgz
    rm -f cni-plugins.tgz
  args:
    creates: /opt/cni/bin/bridge

# 6. Користувач та права
- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Create devops user
  user:
    name: devops
    shell: /bin/bash
    groups: docker,sudo
    append: yes
    create_home: yes

- name: Allow devops user sudo without password
  copy:
    content: "devops ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/devops
    mode: '0440'
