# .github/workflows/rollback.yml
name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        type: choice
        options:
          - dev
          - release
      vm_ip:
        description: 'IP of target VM'
        required: true
        type: string

jobs:
  rollback:
    name: Rollback version
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ github.event.inputs.vm_ip }} >> ~/.ssh/known_hosts

      - name: Execute Rollback on VM
        run: |
          ENV="${{ github.event.inputs.environment }}"
          VM_IP="${{ github.event.inputs.vm_ip }}"

          # Визначаємо параметри залежно від вибору
          if [ "$ENV" == "dev" ]; then
            DEP="devops-app-dev"
            NS="dev"
          else
            DEP="devops-app-release"
            NS="release"
          fi

          echo "Starting rollback for $DEP in namespace $NS..."

          # Виконуємо відкат локально на сервері
          ssh root@$VM_IP << EOF
            kubectl rollout undo deployment/$DEP -n $NS
            kubectl rollout status deployment/$DEP -n $NS --timeout=60s
            echo "--- Rollback History ---"
            kubectl rollout history deployment/$DEP -n $NS
          EOF

      - name: Cleanup
        if: always()
        run: rm -rf ~/.ssh/id_rsa
